---
date: "2020-02-25"
external_link: ""
image: 
  caption: Photo by Kenneth Thorø Martinsen
  focal_point: Smart
links:
slides: 
summary: Developing an automatic floating chamber for carbon dioxide flux measurements
tags:
- carbon dioxide
- climate change
- small lakes
- COWIfonden
title: New method for measuring carbon dioxide flux
url_code: ""
url_pdf: "https://curis.ku.dk/ws/files/203281341/A_simple_and_cost_efficient_automated_floating_chamber_for_continuous_measurements_of_carbon_dioxide_gas_flux_on_lakes.pdf"
url_slides: ""
url_video: ""
---

### Why and how to measure carbon dioxide (CO~2~) flux?

Dissolved gasses are exchanged across the air-water interface. The flux, is the product of the gas exchange velocity and the concentration difference between air and water The gas exchange velocity depends on the turbulence, higher turbulence e.g due to higher wind speeds increase the rate of exchange. If the concentration in the water exceeds that of the air, CO~2~ is emitted to the atmosphere and vice versa. In the face of climate change, it is interesting whether freshwaters are sources or sinks of CO~2~.  

The CO~2~ flux can be measured using floating chambers. This is an inverted bucket, where the CO~2~ concentration is measured. The flux is calculated by knowing the change in concentration over time and the chamber dimensions. Traditionally, these measurements have been performed manually and samples analyzed by gas chromatography. Recently, small cheap sensors for indoor air-quality measurements have made this method much easier. 

### Building an automatic floating chamber

Even if the CO~2~ concentration within the chamber are now easy to measure, the method still require manual labor. Flux measurements are performed over short time spans (from minutes to an hour), requiring manual lifting of the chamber in order to reset the chamber. To avoid this, and at the same time enabling us to do continuous measurements automatically, I have developed an automatic solution. This solution uses a timer and small air-pump which regularly flushes the chamber headspace with atmospheric air. We reported on this method in  [Biogeosciences](https://www.biogeosciences.net/15/5565/2018/).  

The new automatic floating chamber has been central for later investigations of CO~2~ fluxes in small lakes:  

* [Carbon dioxide efflux and ecosystem metabolism of small forest lakes](https://link.springer.com/article/10.1007/s00027-019-0682-8)  
* [Carbon dioxide fluxes of air-exposed sediments and desiccating ponds](https://link.springer.com/article/10.1007/s10533-019-00579-0)  
* [Danish popular science articles: Bedre og billigere teknologi til studier af klimagasser](http://www.vand-og-jord.dk/vj218.htm)  

This project was funded by [COWIfonden](https://www.cowifonden.com/donations/recent-projects/donations-2017).
